version: "3.9"

services:
  node_dapp:
    container_name: node_dapp
    build: .
    image: web3-login-app
    ports:
      - "8080:8080"
    environment:
      - PG_PASSWORD=12345678
      - PG_USER=postgres
      - PG_DB=wallet-login
      - PG_HOST=localhost
    depends_on:
      - node_db
    restart: always
  
  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wallet-login
